# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(835, 583)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color: #435055;\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    color:#FFFFFF;\n"
"    border-radius:6px;\n"
"    background-color:  #27323A;\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    padding-top:5px;\n"
"    padding-bottom:5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(92, 109, 121);\n"
"}\n"
"QLineEdit{\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid #29A19C;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setStyleSheet("#menu_pushButton{\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"}\n"
"#menu_pushButton_home_s{\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"    border-top-right-radius:0px;\n"
"    border-bottom-right-radius:0px;\n"
"}\n"
"#menu_pushButton_home_l{\n"
"    border-top-left-radius:0px;\n"
"    border-bottom-left-radius:0px;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"}\n"
"#menu_pushButton_add_symbol_s{\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"    border-top-right-radius:0px;\n"
"    border-bottom-right-radius:0px;\n"
"}\n"
"#menu_pushButton_add_symbol_l{\n"
"    border-top-left-radius:0px;\n"
"    border-bottom-left-radius:0px;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"}")
        self.menu.setObjectName("menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout_2.setContentsMargins(-1, 25, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.menu_pushButton = QtWidgets.QPushButton(self.menu)
        self.menu_pushButton.setMinimumSize(QtCore.QSize(60, 40))
        self.menu_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/templates/images/menu-navigation-grid-white.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_pushButton.setIcon(icon)
        self.menu_pushButton.setIconSize(QtCore.QSize(24, 24))
        self.menu_pushButton.setObjectName("menu_pushButton")
        self.verticalLayout_2.addWidget(self.menu_pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menu_pushButton_home_s = QtWidgets.QPushButton(self.menu)
        self.menu_pushButton_home_s.setMinimumSize(QtCore.QSize(60, 40))
        self.menu_pushButton_home_s.setMaximumSize(QtCore.QSize(60, 40))
        self.menu_pushButton_home_s.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/templates/images/home-white.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_pushButton_home_s.setIcon(icon1)
        self.menu_pushButton_home_s.setIconSize(QtCore.QSize(24, 24))
        self.menu_pushButton_home_s.setObjectName("menu_pushButton_home_s")
        self.horizontalLayout_4.addWidget(self.menu_pushButton_home_s)
        self.menu_pushButton_home_l = QtWidgets.QPushButton(self.menu)
        self.menu_pushButton_home_l.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menu_pushButton_home_l.setFont(font)
        self.menu_pushButton_home_l.setObjectName("menu_pushButton_home_l")
        self.horizontalLayout_4.addWidget(self.menu_pushButton_home_l)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.menu_pushButton_add_symbol_s = QtWidgets.QPushButton(self.menu)
        self.menu_pushButton_add_symbol_s.setMinimumSize(QtCore.QSize(60, 40))
        self.menu_pushButton_add_symbol_s.setMaximumSize(QtCore.QSize(60, 40))
        self.menu_pushButton_add_symbol_s.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/templates/images/add-file-white.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_pushButton_add_symbol_s.setIcon(icon2)
        self.menu_pushButton_add_symbol_s.setIconSize(QtCore.QSize(24, 24))
        self.menu_pushButton_add_symbol_s.setObjectName("menu_pushButton_add_symbol_s")
        self.horizontalLayout_5.addWidget(self.menu_pushButton_add_symbol_s)
        self.menu_pushButton_add_symbol_l = QtWidgets.QPushButton(self.menu)
        self.menu_pushButton_add_symbol_l.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menu_pushButton_add_symbol_l.setFont(font)
        self.menu_pushButton_add_symbol_l.setObjectName("menu_pushButton_add_symbol_l")
        self.horizontalLayout_5.addWidget(self.menu_pushButton_add_symbol_l)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addWidget(self.menu, 0, QtCore.Qt.AlignTop)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.main = QtWidgets.QWidget(self.centralwidget)
        self.main.setObjectName("main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_topBar = QtWidgets.QWidget(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_topBar.sizePolicy().hasHeightForWidth())
        self.main_topBar.setSizePolicy(sizePolicy)
        self.main_topBar.setStyleSheet("#title{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.main_topBar.setObjectName("main_topBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_topBar)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.title = QtWidgets.QLabel(self.main_topBar)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title.setFrameShadow(QtWidgets.QFrame.Plain)
        self.title.setOpenExternalLinks(False)
        self.title.setObjectName("title")
        self.horizontalLayout_2.addWidget(self.title, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.main_topBar)
        self.main_container = QtWidgets.QWidget(self.main)
        self.main_container.setStyleSheet("#wallet_list{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"}")
        self.main_container.setObjectName("main_container")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.main_container)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_container)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_wallet = QtWidgets.QWidget()
        self.page_wallet.setStyleSheet("#page_wallet{\n"
"background-color: #435055;\n"
"}    \n"
"")
        self.page_wallet.setObjectName("page_wallet")
        self.verticalLayout_page_wallet = QtWidgets.QVBoxLayout(self.page_wallet)
        self.verticalLayout_page_wallet.setObjectName("verticalLayout_page_wallet")
        self.symbol_row_section = QtWidgets.QWidget(self.page_wallet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.symbol_row_section.sizePolicy().hasHeightForWidth())
        self.symbol_row_section.setSizePolicy(sizePolicy)
        self.symbol_row_section.setObjectName("symbol_row_section")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.symbol_row_section)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.symbol_row_section)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.line = QtWidgets.QFrame(self.symbol_row_section)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_7.addWidget(self.line)
        self.comboBox = QtWidgets.QComboBox(self.symbol_row_section)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox)
        self.line_2 = QtWidgets.QFrame(self.symbol_row_section)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_7.addWidget(self.line_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.symbol_row_section)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_2)
        self.line_3 = QtWidgets.QFrame(self.symbol_row_section)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_7.addWidget(self.line_3)
        self.comboBox_3 = QtWidgets.QComboBox(self.symbol_row_section)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_3)
        self.verticalLayout_page_wallet.addWidget(self.symbol_row_section)
        self.wallet_list = QtWidgets.QListWidget(self.page_wallet)
        self.wallet_list.setObjectName("wallet_list")
        self.verticalLayout_page_wallet.addWidget(self.wallet_list)
        self.stackedWidget.addWidget(self.page_wallet)
        self.page_add_symbol = QtWidgets.QWidget()
        self.page_add_symbol.setObjectName("page_add_symbol")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.page_add_symbol)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget = QtWidgets.QWidget(self.page_add_symbol)
        self.widget.setObjectName("widget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_symbol_name = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_symbol_name.setMinimumSize(QtCore.QSize(200, 35))
        self.lineEdit_symbol_name.setMaximumSize(QtCore.QSize(200, 35))
        self.lineEdit_symbol_name.setObjectName("lineEdit_symbol_name")
        self.horizontalLayout_6.addWidget(self.lineEdit_symbol_name)
        self.lineEdit_symbol_exchange = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_symbol_exchange.setMinimumSize(QtCore.QSize(200, 35))
        self.lineEdit_symbol_exchange.setMaximumSize(QtCore.QSize(200, 35))
        self.lineEdit_symbol_exchange.setObjectName("lineEdit_symbol_exchange")
        self.horizontalLayout_6.addWidget(self.lineEdit_symbol_exchange)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_symbol_cost = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_symbol_cost.setMinimumSize(QtCore.QSize(200, 35))
        self.lineEdit_symbol_cost.setMaximumSize(QtCore.QSize(200, 35))
        self.lineEdit_symbol_cost.setObjectName("lineEdit_symbol_cost")
        self.horizontalLayout_8.addWidget(self.lineEdit_symbol_cost)
        self.lineEdit_symbol_lot = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_symbol_lot.setMinimumSize(QtCore.QSize(200, 35))
        self.lineEdit_symbol_lot.setMaximumSize(QtCore.QSize(200, 35))
        self.lineEdit_symbol_lot.setObjectName("lineEdit_symbol_lot")
        self.horizontalLayout_8.addWidget(self.lineEdit_symbol_lot)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.comboBox_4 = QtWidgets.QComboBox(self.widget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_4, 0, QtCore.Qt.AlignRight)
        self.pushButton_add_symbol = QtWidgets.QPushButton(self.widget)
        self.pushButton_add_symbol.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_add_symbol.setObjectName("pushButton_add_symbol")
        self.verticalLayout_3.addWidget(self.pushButton_add_symbol, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        self.horizontalLayout_10.addWidget(self.widget, 0, QtCore.Qt.AlignTop)
        self.stackedWidget.addWidget(self.page_add_symbol)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.main_container)
        self.horizontalLayout.addWidget(self.main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_pushButton_home_l.setText(_translate("MainWindow", "HOME"))
        self.menu_pushButton_add_symbol_l.setText(_translate("MainWindow", "SEMBOL EKLE"))
        self.title.setText(_translate("MainWindow", "ANASAYFA"))
        self.label_5.setText(_translate("MainWindow", "Sembol"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Tavan"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Yüksek"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Düşük"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Taban"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Kapanış"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Fark"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Kar"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Kar(%)"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Tavan"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Yüksek"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Düşük"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Taban"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Kapanış"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Fark"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "Kar"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "Kar(%)"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Tavan"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Yüksek"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Düşük"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Taban"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Kapanış"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "Fark"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "Kar"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "Kar(%)"))
        self.lineEdit_symbol_name.setPlaceholderText(_translate("MainWindow", "Sembol"))
        self.lineEdit_symbol_exchange.setPlaceholderText(_translate("MainWindow", "Borsa (BIST, NASDAQ)"))
        self.lineEdit_symbol_cost.setPlaceholderText(_translate("MainWindow", "Maliyet"))
        self.lineEdit_symbol_lot.setPlaceholderText(_translate("MainWindow", "Lot"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Turkey"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Amerika"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Australia"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Brazil"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "CFD"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "Canada"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "Cryptocurrency"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "Euronext"))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "Forex"))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "France"))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "Germany"))
        self.comboBox_4.setItemText(11, _translate("MainWindow", "Hong Kong"))
        self.comboBox_4.setItemText(12, _translate("MainWindow", "India"))
        self.comboBox_4.setItemText(13, _translate("MainWindow", "Indonesia"))
        self.comboBox_4.setItemText(14, _translate("MainWindow", "Italy"))
        self.comboBox_4.setItemText(15, _translate("MainWindow", "Malaysia"))
        self.comboBox_4.setItemText(16, _translate("MainWindow", "Philippines"))
        self.comboBox_4.setItemText(17, _translate("MainWindow", "Russia"))
        self.comboBox_4.setItemText(18, _translate("MainWindow", "Saudi Arabia"))
        self.comboBox_4.setItemText(19, _translate("MainWindow", "South Africa"))
        self.comboBox_4.setItemText(20, _translate("MainWindow", "South Korea"))
        self.comboBox_4.setItemText(21, _translate("MainWindow", "Spain"))
        self.comboBox_4.setItemText(22, _translate("MainWindow", "Sweden"))
        self.comboBox_4.setItemText(23, _translate("MainWindow", "Taiwan"))
        self.comboBox_4.setItemText(24, _translate("MainWindow", "Thailand"))
        self.comboBox_4.setItemText(25, _translate("MainWindow", "United Kingdom"))
        self.comboBox_4.setItemText(26, _translate("MainWindow", "Vietnam"))
        self.pushButton_add_symbol.setText(_translate("MainWindow", "Sembol Ekle"))
import images_rc
