# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 600)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_bg = QtWidgets.QWidget(Form)
        self.widget_bg.setStyleSheet("#widget_bg{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:30px;}")
        self.widget_bg.setObjectName("widget_bg")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_bg)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_status = QtWidgets.QWidget(self.widget_bg)
        self.widget_status.setMinimumSize(QtCore.QSize(0, 200))
        self.widget_status.setMaximumSize(QtCore.QSize(16777215, 200))
        self.widget_status.setStyleSheet("#widget_status{\n"
"    background-color: rgb(43, 180, 39);\n"
"    border-radius:30px;\n"
"}")
        self.widget_status.setObjectName("widget_status")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_status)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.status_icon = QtWidgets.QLabel(self.widget_status)
        self.status_icon.setMinimumSize(QtCore.QSize(150, 150))
        self.status_icon.setMaximumSize(QtCore.QSize(150, 150))
        self.status_icon.setText("")
        self.status_icon.setObjectName("status_icon")
        self.horizontalLayout_2.addWidget(self.status_icon, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.widget_status)
        self.widget_info = QtWidgets.QWidget(self.widget_bg)
        self.widget_info.setObjectName("widget_info")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_info)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.widget_info)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.message_code = QtWidgets.QLabel(self.widget_2)
        self.message_code.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Garuda")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.message_code.setFont(font)
        self.message_code.setLineWidth(1)
        self.message_code.setAlignment(QtCore.Qt.AlignCenter)
        self.message_code.setWordWrap(True)
        self.message_code.setOpenExternalLinks(False)
        self.message_code.setObjectName("message_code")
        self.verticalLayout_2.addWidget(self.message_code)
        self.title = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setMinimumSize(QtCore.QSize(0, 40))
        self.title.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout_2.addWidget(self.title)
        self.message = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.message.setFont(font)
        self.message.setAlignment(QtCore.Qt.AlignCenter)
        self.message.setObjectName("message")
        self.verticalLayout_2.addWidget(self.message)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_buttons = QtWidgets.QWidget(self.widget_info)
        self.widget_buttons.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget_buttons.setStyleSheet("#pushButton_ok{\n"
"border:None;\n"
"border-radius:15px;\n"
"background-color: rgb(43, 180, 39);\n"
"color:#FFFFFF;\n"
"}\n"
"#pushButton_cancel{\n"
"border:None;\n"
"border-radius:15px;\n"
"background-color: rgb(231, 24, 24);\n"
"color:#FFFFFF;\n"
"}")
        self.widget_buttons.setObjectName("widget_buttons")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_buttons)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 30)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_ok = QtWidgets.QPushButton(self.widget_buttons)
        self.pushButton_ok.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_ok.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ok.setFont(font)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_3.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.widget_buttons)
        self.pushButton_cancel.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_cancel.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_3.addWidget(self.pushButton_cancel)
        self.verticalLayout_3.addWidget(self.widget_buttons)
        self.verticalLayout.addWidget(self.widget_info)
        self.horizontalLayout.addWidget(self.widget_bg)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.message_code.setText(_translate("Form", "100"))
        self.title.setText(_translate("Form", "TITLE"))
        self.message.setText(_translate("Form", "Message"))
        self.pushButton_ok.setText(_translate("Form", "CONTINUE"))
        self.pushButton_cancel.setText(_translate("Form", "TRY AGAIN"))
